server:
  port: ${PORT:5000}

base-url: /api

spring:
  profiles:
    active: ${APP_ENV:dev}

  application:
    name: Task Manager

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  jpa:
    hibernate:
      ddl-auto: validate

springdoc:
  swagger-ui:
    path: /swagger.html